name: talklowkey_mobile
description: "TalkLowKey - A secure messaging and social media platform"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  video_player: ^2.8.1
  photo_view: ^0.14.0
  shimmer: ^3.0.0
  lottie: ^2.7.0

  # State Management
  provider: ^6.1.1
  get: ^4.6.6

  # HTTP & API
  http: ^1.1.0
  dio: ^5.3.2
  connectivity_plus: ^5.0.2

  # Storage & Local Data
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Authentication & Security
  local_auth: ^2.1.7
  crypto: ^3.0.3

  # Location Services
  geolocator: ^10.1.0
  geocoding: ^2.1.1

  # Real-time Communication
  web_socket_channel: ^2.4.0
  socket_io_client: ^2.0.3+1

  # Media & File Handling
  file_picker: ^6.1.1
  path_provider: ^2.1.1
  permission_handler: ^11.0.1

  # Notifications
  flutter_local_notifications: ^16.3.0
  firebase_messaging: ^14.7.10

  # Utilities
  intl: ^0.18.1
  url_launcher: ^6.2.1
  package_info_plus: ^4.2.0
  device_info_plus: ^9.1.1
  flutter_secure_storage: ^9.0.0

  # UI Enhancements
  flutter_staggered_grid_view: ^0.7.0
  pull_to_refresh: ^2.0.0
  infinite_scroll_pagination: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700 